/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/profile-navigation`; params?: Router.UnknownInputParams; } | { pathname: `/frontscreen/Signupscreen`; params?: Router.UnknownInputParams; } | { pathname: `/frontscreen/Loginscreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/frontscreen/ChangePasswordscreen`; params?: Router.UnknownInputParams; } | { pathname: `/frontscreen/ForgotPasswordscreen`; params?: Router.UnknownInputParams; } | { pathname: `/frontscreen/ResetCodescreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Homescreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Mapscreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Matchscreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Workoutscreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/ProfileApiService/ProfileApiService`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/ProfileApiService/Profilescreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/ProfileApiService/UserSchedule`; params?: Router.UnknownInputParams; } | { pathname: `/utils/util`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-navigation`; params?: Router.UnknownOutputParams; } | { pathname: `/frontscreen/Signupscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/frontscreen/Loginscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/frontscreen/ChangePasswordscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/frontscreen/ForgotPasswordscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/frontscreen/ResetCodescreen`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/Homescreen`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/Mapscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/Matchscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/Workoutscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/ProfileApiService/ProfileApiService`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/ProfileApiService/Profilescreen`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/ProfileApiService/UserSchedule`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/util`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/navigation${`?${string}` | `#${string}` | ''}` | `/profile-navigation${`?${string}` | `#${string}` | ''}` | `/frontscreen/Signupscreen${`?${string}` | `#${string}` | ''}` | `/frontscreen/Loginscreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/frontscreen/ChangePasswordscreen${`?${string}` | `#${string}` | ''}` | `/frontscreen/ForgotPasswordscreen${`?${string}` | `#${string}` | ''}` | `/frontscreen/ResetCodescreen${`?${string}` | `#${string}` | ''}` | `/tabs/Homescreen${`?${string}` | `#${string}` | ''}` | `/tabs/Mapscreen${`?${string}` | `#${string}` | ''}` | `/tabs/Matchscreen${`?${string}` | `#${string}` | ''}` | `/tabs/Workoutscreen${`?${string}` | `#${string}` | ''}` | `/tabs/ProfileApiService/ProfileApiService${`?${string}` | `#${string}` | ''}` | `/tabs/ProfileApiService/Profilescreen${`?${string}` | `#${string}` | ''}` | `/tabs/ProfileApiService/UserSchedule${`?${string}` | `#${string}` | ''}` | `/utils/util${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/profile-navigation`; params?: Router.UnknownInputParams; } | { pathname: `/frontscreen/Signupscreen`; params?: Router.UnknownInputParams; } | { pathname: `/frontscreen/Loginscreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/frontscreen/ChangePasswordscreen`; params?: Router.UnknownInputParams; } | { pathname: `/frontscreen/ForgotPasswordscreen`; params?: Router.UnknownInputParams; } | { pathname: `/frontscreen/ResetCodescreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Homescreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Mapscreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Matchscreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Workoutscreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/ProfileApiService/ProfileApiService`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/ProfileApiService/Profilescreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/ProfileApiService/UserSchedule`; params?: Router.UnknownInputParams; } | { pathname: `/utils/util`; params?: Router.UnknownInputParams; };
    }
  }
}
